
capiblanco = "El mirlo capiblanco (Turdus torquatus) es una especie de Aves paseriforme de la familia Turdidae del género Turdus.\
				Está estrechamente emparentado con el mirlo común (Turdus merula) del que se diferencia fácilmente por la zona de plumaje blanco que destaca sobre su pecho a modo de babero. El resto del cuerpo es negro en el caso de los machos, mientras que las hembras son pardas y provistas de un babero por estar salpicado de plumas leonadas. Los bordes de las alas son más pálidos que el resto del cuerpo. Todos los jóvenes de menos de un año presentan la coloración femenina, independientemente de su sexo.\
				Algunas de las plumas se vuelven grisáceas en otoño, dándole un aspecto escamoso a esta especie. \
				El canto está formado por varias frases cortas que se repiten de 2 a 4 veces (tac-tac-tac, chuc-chuc-chuc-chuc), generalmente en una rama o el suelo, aunque a veces también se produce en pleno vuelo. En este caso el sonido se produce una sola vez, siendo parecido a un chuirrr. \
				El mirlo capiblanco habita en zonas de montaña, donde sustituye al mirlo común. Su hábitat característico es el bosque subalpino aclarado, con preferencia por los de pino negro. Se reproduce en las Islas Británicas, Escandinavia, Pirineos, varias localidades de Europa central y el Cáucaso. Al final del verano emigra hacia el sur para pasar el invierno, llegando hasta el norte de África. En España inverna en los montes de Teruel, la serranía de Ronda (Málaga) y la sierra de Tramontana (Mallorca), preferentemente en zonas cubiertas de Sabinas (botánica), cuyos frutos ingiere en esta época.\
				Los mirlos capiblancos se reúnen en grupos mayores durante el invierno, mientras que el resto del año llevan una vida solitaria o en grupos pequeños.\
				Se alimenta  de insectos, Lumbricidae de tierra, frutos de sabina y otros frutos silvestres.\
				Retorna a sus áreas de cría entre marzo y abril. Durante la época de reproducción deposita numerosos huevo en nidos confeccionados sobre las ramas de un arbusto."

bengala = 	"El tigre de Bengala (Panthera tigris tigris), también conocido como tigre de Bengala real o tigre indio es una subespecie de tigre que habita en la India, Nepal, Bangladés, Bután, Birmania y Tíbet. Es la subespecie más numerosa y conocida de tigre, y se encuentra en una gran variedad de hábitats, incluyendo sabanas y bosques tropicales y subtropicales. Su piel es generalmente de color naranja o leonado. Existe una mutación genética que produce que la piel naranja del tigre sea sustituida por el color blanco; a estos tigres se les conoce como tigres blancos. Una mutación aún más rara (de la que existen menos de cien ejemplares, todos en cautiverio), se conoce como tigre dorado. El tigre es un animal nacional en la India y Bangladés.\
				En 2017 un equipo de investigadores pertenecientes a la UICN publicaron una nueva clasificación taxonómica de la familia felidae en la que solo reconocían a dos subespecies de tigres, el tigre de Asia continental (Panthera tigris tigris) el cual agrupa al tigre de bengala, siberiano, de indochina, sur de China, malayo así como el tigre extinto del Caspio y los tigres de la sonda (Panthera tigris sondaica) que agrupa al tigre de Sumatra así como a los ya desaparecidos tigres de Java y Bali, esta evaluación se basa en una extensa revisión de publicaciones recientes sobre la morfología del tigre y su filogeografía.\
				Anteriormente se le consideraba la segunda subespecie en tamaño, detrás del tigre siberiano (Panthera tigris altaica), sin embargo estudios recientes sugieren que en la actualidad, esta podría ser la subespecie de mayor tamaño. La longitud total de los machos es de 270-310 cm, mientras que la de las hembras es de 240-265 cm; la cola mide unos 85-100 cm de largo y la altura a los hombros de 90-110 cm. El peso depende de la región, algunos tigres están por debajo de los 100 kg mientras que otros llegan a los 230 kg en el caso de los machos. En Chitwal 7 tigres machos arrojaron un promedio de 221 kg. Sin embargo, aquellos machos que habitan el Centro de India, tienen un peso de entre 160 a 233 kg, y un promedio de 190 kg para los machos y de 131 kg para las hembras. Aunque se conoció un gran macho del parque nacional Ranthambore de nombre Ustad (T24) al que se le adjudican la muerte de cuatro personas entre 2010 y 2015 llegó a los 250 kg de peso.\
				El tigre de Bengala más pesado, confirmado en los récords de caza, fue un macho de 258.6 kg, cazado al norte de India en 1938, sin embargo los machos más pesados, registrados por científicos hasta ahora, son dos tigres (M105 y M026) de más de 270 kg, capturados en Nepal, en 1980 y 1984, respectivamente. El tigre de Bengala más grande, medido entre las curvas, fue un macho cazado por Archibald Dunbar Brander, el cual alcanzó los 221 cm de longitud cabeza-cuerpo, con una circunferencia de pecho de 150 cm, una altura a los hombros de 109 cm y una cola de tan solo 81 cm, probablemente cercenada por un macho rival. Si bien este ejemplar no pudo ser pesado, se calculó que su masa corporal no seria menor a los 272 kg.\
				Según los Récords Mundiales Guinness, el tigre de Bengala de mayor tamaño conocido fue un gran macho cazado en 1967, midió 322 cm de largo total en línea recta (338 cm entre las curvas del lomo) y pesó 388.7 kg. Aunque esto no se considera un peso científicamente correcto dado que sus medidas no coinciden con su peso y en las fotos el tigre no goza de gran tamaño, así que es muy posible que su peso real sea mucho más bajo, el ejemplar fue cazado al norte de India por David Hasinger, un industrial de Filadelfia. Actualmente este ejemplar se encuentra exhibido en el Instituto Smithsoniano, en el salón de los Mamíferos. A principios del siglo XX se reportaron ejemplares machos que alcanzaron los 360 cm de longitud total, sin embargo no existe corroboración científica de tales tamaños y los más probable es que fueron medidos sobre las curvas del lomo.\
				Como todos los tigres, son animales solitarios y generalmente no viven en grupos, a excepción de las hembras, que viajan con sus crías en grupos de tres o cuatro. Los machos cuidan un territorio donde viven varias hembras con las que se aparean. Los machos y las hembras solo se reúnen durante la época de reproducción, si bien se han mencionado casos de machos que alimentan a sus crías cuando la madre ha fallecido. La mayoría de las crías nacen entre febrero y mayo, y tras una gestación de entre 98 y 108 días, dan a luz una camada de uno a seis cachorros (normalmente de dos a cuatro) de 1.1 kg de peso. La esperanza de vida para los tigres de Bengala machos es de entre diez y doce años, mientras que para las hembras es un poco más larga; aunque una tigresa del parque nacional de Ranthambore (India) conocida como Machli murió en agosto de 2016 a la avanzada edad de diecinueve años. Algunos ejemplares en cautividad pueden llegar a vivir hasta veintiséis años. Aproximadamente el 25 % de los tigres machos del Parque Nacional de Kanha mueren en luchas con otros tigres.\
				Los machos y hembras solo se unen en periodos reproductivos. El celo difiere según las condiciones climáticas de la zona en que habitan. La reproducción es vivípara y la gestación dura alrededor de noventa y tres a cientodoce días. La madurez sexual del tigre la alcanza recién a los cuatro o cinco años de edad. La madre permanece junto a sus cachorros, que nacen con los ojos cerrados, durante casi dos años, enseñándoles todos los secretos de la caza y la supervivencia. La camada es entre uno y seis cachorros.\
				En un estudio llevado a cabo en la Reserva de tigres Ranthambore entre 2005 y 2010 sobre los tigres de bengala de los bosques caducifolios secos del norte de la India un grupo de investigadores estudiaron a 13 hembras adultas, estableciendo que dos de ellas se reprodujeron por primera vez a la edad de 33 y 48 meses. El intervalo entre los partos de las tigresas estudiadas fue de 33,4 meses sin mucha diferencia entre los sexos de las crías, aunque la cantidad de cachorros machos fue ligeramente mayor. El intervalo entre los nacimientos de cachorros de los tigres de Ranthambore es significativamente mayor que el plazo que existe entre otras poblaciones de tigres estudiadas como las del Parque nacional de Chitwan en Nepal donde el intervalo entre nacimientos fue de 21,6 meses o la Reserva de tigres Pench en India donde es de 25,2 meses, según los investigadores que participaron en el estudio este plazo mas largo entre alumbramientos podría deberse a las condiciones climáticas adversas presentes en Ranthambore durante el verano y a las bajas precipitaciones anuales (800 mm al año), sin embargo el tamaño de las camadas es similar a la de otras poblaciones de tigre (1 a 3 cachorros). La tasa de mortalidad en los cachorros de hasta 12 mese de edad monitoreados en el estudio fue baja (de 15%) en contraste con los índices de mortalidad en cachorros de ambientes mas tropicales (hasta 34%), mientras que los tigres juveniles de entre 12 y 24 meses de edad tuvieron un índice de mortalidad del 6% en Ranthambore y un 17% en otras regiones.\
				Los tigres de Bengala son carnívoros y cazan desde pavos reales hasta búfalos asiáticos y gaures (incluyendo los grandes machos que alcanzan los 1000 kg de peso), pasando por toda una gama de presas que incluye monos, jabalíes, tapires, ciervos y antílopes. Se han reportado casos más raros en que los tigres han atacado a crías de rinoceronte y elefante, e incluso de individuos que fueron capaces de abatir y devorar a otros grandes carnívoros como leopardos y osos. Mucho más raros son los ataques contra humanos, aunque hasta hace un siglo se sucedían con cierta frecuencia. Se calcula que solo en Bangladesh se producen unos cien ataques al año.\
				La mayor parte de tigres de Bengala, casi un tercio de la población mundial de estos grandes felinos, habita en la India y Bangladés. Los parques nacionales de estos países como Parque Nacional de Sundarbans y Ranthambore albergan la mayor parte de estos. También hay una población importante en Nepal, principalmente en el parque Chitawan.\
				Su pelaje superior es de color naranja rojizo con rayas negras o grises, mientras las partes inferiores son blancas. Debido a una mutación genética, algunos tigres en vez de tener pelos naranjas, los tienen en color blanco. Por este motivo se los llaman tigres blancos Otros, en cambio, son conocidos como tigres dorados, producto de otra mutación, pero estos solo son vistos en cautiverio.\
				El acelerado crecimiento de población humana en el mundo ha hecho que el tigre de Bengala se vea amenazado en su propio hábitat natural. Estos son extinguidos por cazadores furtivos, argumentando que representan un peligro para el hombre, pero al mismo tiempo aprovechan sus pieles o sus cuerpos enteros para ser disecados. Organizaciones mundiales como el Fondo Mundial para la Naturaleza trabajan para detener la caza furtiva y reducir los constantes peligros a los que dicho animal se expone. Para 2014 la población del tigre de bengala en la India era de alrededor de 2226 individuos."

sileno = 	"El sileno, macaco de cola de león, mono león o mono barbudo (Macaca silenus) es una especie de primate catarrino de la familia Cercopithecidae. Es endémico de los Ghats occidentales (suroeste de India) y se encuentra en peligro de extinción, con una población total de menos de 4000 ejemplares (probablemente en torno a 2500).\
				Como otros monos del sur y este de Asia, esta especie es preferentemente arborícola, aunque no tiene el menor problema para moverse por el suelo si es necesario. El pelo recubre todo el cuerpo salvo cara, manos y pies, que al igual que este son negros; es más largo en la espalda y sobre todo a los lados de la cara, donde destaca una voluminosa barba de pelo claro. Mide hasta 60 cm de la cabeza al inicio de la cola, midiendo ésta más de la mitad de la longitud del cuerpo y teniendo un mechón de pelo más largo en el extremo. De complexión delgada y alargada, este mono tiene un peso de apenas 3 a 10 kg, lo que le convierte en uno de los macacos más pequeños que existen.\
				Su hábitat exclusivo es el lluvioso bosque tropical que se extiende por las montañas de la punta sur de la India hasta los 1500 metros de altitud. Son diurnos, pero se muestran enormemente desconfiados con el hombre y huyen de él ante la mínima aproximación, lo que contrasta fuertemente con el exhibicionismo de muchos otros primates en India. Los silenos (nombre que toman de Sileno, el rey de los sátiros del bosque en la mitología griega) son animales sociales con una rígida estructura jerárquica, que viven en grupos de 10 a 20 individuos. Las hembras siempre superan en número a los machos, aunque son éstos los que dirigen el grupo y se encargan de defender el territorio (que puede llegar a las 130 ha) frente a otros grupos rivales. La mayoría de las veces basta con un coro de gritos para evitar los enfrentamientos, pero cuando éstos no dan resultado su agresividad aumenta considerablemente. Tienen una dieta omnívora formada por la ingesta de frutos, semillas, flores y pequeños animales.\
				Tras aproximadamente seis meses de gestación, las hembras paren una sola cría que cuidan durante un año. Estas alcanzan la madurez sexual a la edad de 4 años si son hembras o 6 si son machos. Viven unos 20 años en libertad, aunque en cautividad pueden superar la treintena.\
				Los silenos se encuentran entre los primates más raros y amenazados en la actualidad, debido fundamentalmente a la pérdida y fragmentación de su hábitat. La mayoría de las poblaciones actuales se concentra en pequeños bosques aislados del resto, lo que complica su permanencia a largo plazo. Por esta razón, muchos parques zoológicos de todo el mundo están llevando a cabo programas de cría en cautividad."

babosa =		"La babosa amarilla.\
				Es un insecto que se hace presente haciendo alusión al dinero, y a la prosperidad que pronto estaría llegando al hogar. Dependiendo de sus tonos de colores estas significan distintas cosas.\
				Esta babosa tiene un cuerpo de color amarillo con manchas grises. La longitud del cuerpo puede ser de 7,5 a 10 cm.\
				La babosa amarilla es común en Inglaterra, Gales e Irlanda, así como la mayor parte del sur y el oeste de Europa.\
				También se puede encontrar fuera de Europa, por ejemplo, en Asia o América del Sur debido a introducción accidental.\
				Esta especie está fuertemente asociada con los asentamientos humanos, y se encuentra normalmente en zonas húmedas, como sótanos, cocinas, y jardines. En términos generales, es visto sólo por la noche, porque es nocturna.\
				Se trata de un molusco terrestre que se alimenta sobre todo de hongos, materia en descomposición, verduras.\
				A veces las babosas amarillas son depredadas por mapaches, gansos, patos, serpientes de jardín, salamandras, topos y musarañas."

estrella = 	"La corona de espinas o acantáster púrpura (Acanthaster planci) es una especie de estrella de mar, de la familia Acanthasteridae, orden Valvatida.\
				Esta estrella de mar se alimenta casi exclusivamente de corales duros, representando en algunas áreas, como la Gran Barrera de Arrecifes australiana,  una de las amenazas importantes para la supervivencia de los arrecifes, ya que un ejemplar de tamaño medio, devora 478 cm² de coral vivo por día.\
				Esta estrella de mar varia su coloración del marrón oscuro grisáceo al rojo, naranja o púrpura, con la punta de sus espinas en rojo o amarillo, y los pies ambulacrales en beige. Estas diferencias de coloración se estima que se deben a su dieta. Posee entre 8 y 21 brazos que radian de un disco central. Las puntas de los brazos tienen células foto-receptoras, que sólo distinguen sombras o luz. Los pies ambulacrales son táctiles, y, aparte de su función locomotora, le sirven para percibir el entorno.\
				La boca se sitúa en el centro de su parte inferior, o aboral. El interior del cuerpo contiene el estómago, la glándula digestiva y las gónadas. El esqueleto está compuesto de pequeñas estructuras llamadas osículos, hechas de calcita de magnesio.\
				Está provista de espinas por todo el cuerpo que le proporcionan una buena defensa contra sus depredadores. El contacto con sus espinas provoca un dolor vivo, que puede durar unas cuatro horas, náuseas y vómitos. A menudo la región afectada alrededor del punto de contacto experimenta una fuerte inflamación con eritrema, cuyo edema puede durar varios días.\
				Puede desplazarse a una velocidad de 20 metros por hora.\
				Su tamaño medio oscila entre 25 y 35 cm de diámetro, y llega a alcanzar un diámetro de 70 cm. Acanthaster plancii ocupa el segundo lugar entre las estrellas de mar más grandes del mundo, tan sólo la estrella girasol (Pycnopodia helianthoides) le supera en tamaño, con un diámetro de hasta 90 cm.\
				Son dióicas, o de sexos separados, ovíparas y de fertilización externa. Los machos y las hembras expulsan sus gametos al agua marina, donde se produce la fertilización. Las hembras gestantes contienen entre 12 y 24 millones de huevos, pudiendo producir hasta 60 millones de huevos en una estación.\
				Desovan estacionalmente durante los meses de verano, de mayo a agosto, en el hemisferio norte, y de noviembre a febrero en el hemisferio sur. Hay evidencias de que A. planci expulsa sustancias químicas al agua para estimular a los individuos cercanos al desove. La operación se materializa trepando a un saliente alto del arrecife, entonces arquea el cuerpo, y los gametos son expulsados a través de cinco poros situados en la parte aboral del cuerpo, según ondea los brazos y mueve sus pies ambulacrales vigorosamente.\
				Los huevos fertilizados evolucionan a larvas planctónicas, dependiendo del fitoplancton para su nutrición. Estas larvas pasan por tres etapas evolutivas: de gastrula a bipinnaria, y a brachiolaria. Al final de la etapa brachiolaria, se asienta en un sustrato duro y se metamorfosea a la forma de estrella de mar juvenil. Comienza desarrollando cinco brazos, pero van aumentando según madura, hasta alcanzar incluso 21. \
				Los investigadores contemplan tres etapas de desarrollo: juvenil, subadulto y adulto. En la primera crecen rápidamente, hasta 16,7 mm por mes, y de subadulto a adulto hasta 4,5 mm por mes.\
				Su expectativa de vida media es de 16 años.\
				Su dieta se constituye principalmente de corales duros, como Acropora, Pavona, Pocillopora o Porites.  Su paso queda marcado por los blancos esqueletos, vacíos de los corales de los que se alimenta. Para devorarlos evagina el estómago, sacándolo del cuerpo por la boca, y digiere los corales con sus secreciones, para absorberlos posteriormente. También se alimenta de algas y detritus.\
				Su hábitat más frecuente son los arrecifes de coral o arrecifes coralinos, especialmente las lagunas , protegidos de fuerte oleaje.\
				Su rango de profundidad es de 1 a 67 m, aunque la media suele hallarse sobre los 10 m.\
				Su rango de temperatura es entre 23.01 y 28.95ºC.\
				Son animales solitarios, que se alimentan en soledad, y que mantienen cierta distancia entre ellos y con los miembros de otras especies.\
				Las fuertes espinas de A. planci le protegen de muchos posibles predadores, no obstante es predada por el caracol gigante Charonia tritonis, así como por peces de las familias Balistidae y Tetraodontidae, que poseen escamas córneas y dientes puntiagudos. Son conocidos predadores los peces Balistoides viridescens, Pseudobalistes flavimarginatus y Arothron hispidus, así como el gusano de fuego Pherecardia striata o la gamba arlequín Hymenocera picta.\
				Esta especie presenta una amplia distribución en toda la región Zona tropical indo-pacífica, desde las costas orientales africanas, el mar Rojo, pasando por el océano Índico, el océano Pacífico oeste, central, y hasta la costa de Panamá y la Isla Gorgona.\
				En la costa francesa mediterránea es especie invasora.\
				Desde mediados del siglo XX se ha observado en las islas Ryukyu y, posteriormente, en la Gran barrera de coral australiana y otros lugares, una multiplicación masiva de estas estrellas de mar, hecho que supone una amenaza para las formaciones coralinas. Debido a que los lugares que ocupaban corales de los que se alimentan son tomados rápidamente por algas y otros corales no formadores de arrecifes, la formación de estos se interrumpe de manera casi definitiva. Este hecho puede llegar a tener serias consecuencias para las costas, debido a que los arrecifes coralinos protegen de los temporales.\
				En su fase planctónica, la estrella está sometida a numerosos riesgos, siendo su principal depredador un tipo de caracol gigante, el caracol tonel. Este animal no es muy abundante, a lo que se suma la descontrolada captura por parte de coleccionistas. Probablemente, la escasez de su depredador natural haya provocado la multiplicación masiva de la estrella."